import type { RoomDef } from "../types";
import { THEMES } from "../themes";
import { SK } from "../palette";

export const ares: RoomDef = {
  agentId: "ares",
  theme: THEMES.warrior,
  character: {
    look: {
      hair: SK.hairBlack,
      shirt: "#ff4adf",
      pants: "#200818",
      accessory: "helmet",
    },
    home: { x: 82, y: 73 },
    face: 1,
  },
  objects: [
    // Wall items (y 8-40)
    {
      id: "a1",
      kind: "WeaponRack",
      x: 12,
      y: 14,
      layer: "wall",
      label: "Weapon Rack",
      scenarios: [
        {
          id: "weapons-selecting",
          label: "Selecting blade",
          anim: "cast",
          stand: { x: 26, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "a2",
      kind: "WeaponRack",
      x: 45,
      y: 12,
      layer: "wall",
      label: "Secondary Arsenal",
      interactive: false,
    },
    {
      id: "a3",
      kind: "BugBoard",
      x: 75,
      y: 10,
      layer: "wall",
      label: "Bug Board",
      scenarios: [
        {
          id: "bug-mapping",
          label: "Mapping failures",
          anim: "stare",
          stand: { x: 89, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "a4",
      kind: "BattleMap",
      x: 110,
      y: 14,
      layer: "wall",
      label: "Battle Map",
      scenarios: [
        {
          id: "map-plotting",
          label: "Plotting counter",
          anim: "stare",
          stand: { x: 104, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "a5",
      kind: "NeonSign",
      x: 50,
      y: 6,
      layer: "wall",
      label: "War Deck Sign",
      props: { text: "WAR DECK" },
      interactive: false,
    },
    {
      id: "a6",
      kind: "Clock",
      x: 25,
      y: 8,
      layer: "wall",
      label: "War Room Clock",
      interactive: false,
    },
    {
      id: "a7",
      kind: "Lantern",
      x: 138,
      y: 16,
      layer: "wall",
      label: "Red Alert Light",
      interactive: false,
    },
    {
      id: "a8",
      kind: "WallArt",
      x: 3,
      y: 18,
      layer: "wall",
      label: "Abstract Pattern",
      props: { variant: "abstract" },
      interactive: false,
    },
    // Floor items (y 48-88)
    {
      id: "a9",
      kind: "TrainingDummy",
      x: 18,
      y: 58,
      label: "Training Dummy",
      scenarios: [
        {
          id: "dummy-drilling",
          label: "Drilling",
          anim: "swing",
          stand: { x: 32, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "a10",
      kind: "FlameSword",
      x: 48,
      y: 62,
      label: "Flame Sword",
      scenarios: [
        {
          id: "sword-testing",
          label: "Testing blade",
          anim: "swing",
          stand: { x: 56, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "a11",
      kind: "PunchingBag",
      x: 76,
      y: 56,
      label: "Punching Bag",
      scenarios: [
        {
          id: "bag-venting",
          label: "Venting steam",
          anim: "swing",
          stand: { x: 70, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "a12",
      kind: "TacticalCRT",
      x: 104,
      y: 54,
      label: "Tactical CRT",
      scenarios: [
        {
          id: "crt-stacktrace",
          label: "Reading stack trace",
          anim: "type",
          stand: { x: 98, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "a13",
      kind: "TacticalCRT",
      x: 130,
      y: 58,
      label: "Secondary CRT",
      interactive: false,
    },
    {
      id: "a14",
      kind: "CRTMonitor",
      x: 12,
      y: 74,
      label: "Alert Monitor",
      props: { variant: "red" },
      interactive: false,
    },
    {
      id: "a15",
      kind: "MedicCabinet",
      x: 42,
      y: 70,
      label: "Medi-Kit",
      scenarios: [
        {
          id: "medic-patching",
          label: "Patching wounds",
          anim: "cast",
          stand: { x: 56, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "a16",
      kind: "SignalMortar",
      x: 68,
      y: 76,
      label: "Signal Mortar",
      scenarios: [
        {
          id: "mortar-firing",
          label: "Firing diagnostic",
          anim: "aim",
          stand: { x: 74, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "a17",
      kind: "CommandConsole",
      x: 95,
      y: 78,
      label: "Command Post",
      interactive: false,
    },
    {
      id: "a18",
      kind: "AmmoCrate",
      x: 125,
      y: 74,
      label: "Ammo Supply",
      interactive: false,
    },
    {
      id: "a19",
      kind: "Rug",
      x: 55,
      y: 84,
      label: "War Room Rug",
      interactive: false,
    },
    {
      id: "a20",
      kind: "CoffeeMug",
      x: 148,
      y: 76,
      label: "Night Shift Coffee",
      interactive: false,
    },
  ],
};
