import type { RoomDef } from "../types";
import { THEMES } from "../themes";
import { SK } from "../palette";

export const echo: RoomDef = {
  agentId: "echo",
  theme: THEMES.relay,
  character: {
    look: {
      hair: SK.hairBrown,
      shirt: "#06b6d4",
      pants: "#0a1a28",
      accessory: "headset",
    },
    home: { x: 78, y: 73 },
    face: 1,
  },
  objects: [
    // Wall items (y 8-40)
    {
      id: "e1",
      kind: "SatelliteDish",
      x: 12,
      y: 8,
      layer: "wall",
      label: "Satellite Dish",
      scenarios: [
        {
          id: "dish-aligning",
          label: "Aligning uplink",
          anim: "cast",
          stand: { x: 26, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "e2",
      kind: "AntennaArray",
      x: 48,
      y: 12,
      layer: "wall",
      label: "Antenna Array",
      scenarios: [
        {
          id: "antenna-tuning",
          label: "Tuning frequency",
          anim: "cast",
          stand: { x: 62, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "e3",
      kind: "BeaconLight",
      x: 80,
      y: 14,
      layer: "wall",
      label: "Beacon Light",
      scenarios: [
        {
          id: "beacon-relaying",
          label: "Relaying alert",
          anim: "transmit",
          stand: { x: 74, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "e4",
      kind: "Oscilloscope",
      x: 110,
      y: 10,
      layer: "wall",
      label: "Signal Scope",
      interactive: false,
    },
    {
      id: "e5",
      kind: "NeonSign",
      x: 50,
      y: 6,
      layer: "wall",
      label: "Relay Sign",
      props: { text: "RELAY" },
      interactive: false,
    },
    {
      id: "e6",
      kind: "Clock",
      x: 20,
      y: 8,
      layer: "wall",
      label: "Network Clock",
      interactive: false,
    },
    {
      id: "e7",
      kind: "Lantern",
      x: 145,
      y: 10,
      layer: "wall",
      label: "Relay Lantern",
      interactive: false,
    },
    {
      id: "e8",
      kind: "WallArt",
      x: 3,
      y: 20,
      layer: "wall",
      label: "Signal Pattern",
      interactive: false,
    },
    // Floor items (y 48-88)
    {
      id: "e9",
      kind: "ServerRack",
      x: 14,
      y: 56,
      label: "Primary Server",
      scenarios: [
        {
          id: "server-restarting",
          label: "Restarting service",
          anim: "cast",
          stand: { x: 28, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "e10",
      kind: "ServerRack",
      x: 42,
      y: 58,
      label: "Backup Server",
      interactive: false,
    },
    {
      id: "e11",
      kind: "Oscilloscope",
      x: 70,
      y: 56,
      label: "Debug Oscilloscope",
      scenarios: [
        {
          id: "scope-debugging",
          label: "Debugging signal",
          anim: "stare",
          stand: { x: 64, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "e12",
      kind: "PigeonCoop",
      x: 104,
      y: 60,
      label: "Pigeon Coop",
      scenarios: [
        {
          id: "pigeon-dispatching",
          label: "Dispatching messenger",
          anim: "cast",
          stand: { x: 98, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "e13",
      kind: "RouterStack",
      x: 136,
      y: 58,
      label: "Router Stack",
      scenarios: [
        {
          id: "router-rerouting",
          label: "Re-routing traffic",
          anim: "type",
          stand: { x: 130, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "e14",
      kind: "CableSnake",
      x: 20,
      y: 72,
      label: "Cable Bundle 1",
      interactive: false,
    },
    {
      id: "e15",
      kind: "CableSnake",
      x: 55,
      y: 76,
      label: "Cable Bundle 2",
      interactive: false,
    },
    {
      id: "e16",
      kind: "ConsoleDesk",
      x: 85,
      y: 74,
      label: "Console Desk",
      scenarios: [
        {
          id: "console-monitoring",
          label: "Monitoring streams",
          anim: "type",
          stand: { x: 79, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "e17",
      kind: "PhoneExchange",
      x: 12,
      y: 80,
      label: "Phone Exchange",
      scenarios: [
        {
          id: "phone-plugging",
          label: "Plugging in line",
          anim: "cast",
          stand: { x: 26, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "e18",
      kind: "Plant",
      x: 120,
      y: 78,
      label: "Relay Plant",
      interactive: false,
    },
    {
      id: "e19",
      kind: "Rug",
      x: 60,
      y: 84,
      label: "Signal Room Rug",
      interactive: false,
    },
    {
      id: "e20",
      kind: "CoffeeMug",
      x: 148,
      y: 76,
      label: "Comms Coffee",
      interactive: false,
    },
  ],
};
