import type { RoomDef } from "../types";
import { THEMES } from "../themes";
import { SK } from "../palette";

export const forge: RoomDef = {
  agentId: "forge",
  theme: THEMES.smith,
  character: {
    look: {
      hair: SK.hairRed,
      shirt: "#ffae3a",
      pants: "#2a1608",
      accessory: "goggles",
    },
    home: { x: 75, y: 72 },
    face: 1,
  },
  objects: [
    // Wall items (y 8-40)
    {
      id: "f1",
      kind: "Forge",
      x: 14,
      y: 16,
      layer: "wall",
      label: "The Forge",
      scenarios: [
        {
          id: "forge-stoking",
          label: "Stoking the fire",
          anim: "cast",
          stand: { x: 28, y: 72 },
          face: 1,
          duration: 5,
        },
      ],
    },
    {
      id: "f2",
      kind: "Anvil",
      x: 42,
      y: 22,
      layer: "wall",
      label: "Main Anvil",
      scenarios: [
        {
          id: "anvil-hammering",
          label: "Hammering hot iron",
          anim: "hammer",
          stand: { x: 54, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "f3",
      kind: "ToolRack",
      x: 72,
      y: 12,
      layer: "wall",
      label: "Tool Rack",
      scenarios: [
        {
          id: "tools-swapping",
          label: "Swapping tools",
          anim: "cast",
          stand: { x: 86, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "f4",
      kind: "ToolRack",
      x: 105,
      y: 14,
      layer: "wall",
      label: "Secondary Tools",
      interactive: false,
    },
    {
      id: "f5",
      kind: "WallArt",
      x: 130,
      y: 10,
      layer: "wall",
      label: "Blueprint Wall",
      props: { variant: "landscape" },
      interactive: false,
    },
    {
      id: "f6",
      kind: "NeonSign",
      x: 50,
      y: 6,
      layer: "wall",
      label: "Foundry Sign",
      props: { text: "FOUNDRY" },
      interactive: false,
    },
    {
      id: "f7",
      kind: "Clock",
      x: 20,
      y: 8,
      layer: "wall",
      label: "Workshop Clock",
      interactive: false,
    },
    {
      id: "f8",
      kind: "Lantern",
      x: 145,
      y: 12,
      layer: "wall",
      label: "Heat Lantern",
      interactive: false,
    },
    // Floor items (y 48-88)
    {
      id: "f9",
      kind: "Workbench",
      x: 18,
      y: 56,
      label: "Assembly Workbench",
      scenarios: [
        {
          id: "bench-assembling",
          label: "Assembling parts",
          anim: "hammer",
          stand: { x: 32, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "f10",
      kind: "BlueprintDesk",
      x: 74,
      y: 58,
      label: "Blueprint Desk",
      scenarios: [
        {
          id: "blueprint-reading",
          label: "Reading specs",
          anim: "read",
          stand: { x: 68, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "f11",
      kind: "CRTMonitor",
      x: 102,
      y: 54,
      label: "Build Terminal",
      props: { variant: "green" },
      scenarios: [
        {
          id: "crt-building",
          label: "Running build",
          anim: "type",
          stand: { x: 96, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "f12",
      kind: "CommandConsole",
      x: 130,
      y: 60,
      label: "Deployment Console",
      scenarios: [
        {
          id: "console-deploying",
          label: "Deploying artifact",
          anim: "type",
          stand: { x: 124, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "f13",
      kind: "ServerRack",
      x: 12,
      y: 76,
      label: "Artifact Storage",
      interactive: false,
    },
    {
      id: "f14",
      kind: "CoinStack",
      x: 40,
      y: 78,
      label: "Material Cache",
      interactive: false,
    },
    {
      id: "f15",
      kind: "AmmoCrate",
      x: 62,
      y: 76,
      label: "Parts Crate",
      interactive: false,
    },
    {
      id: "f16",
      kind: "AmmoCrate",
      x: 88,
      y: 74,
      label: "Supply Crate",
      interactive: false,
    },
    {
      id: "f17",
      kind: "Plant",
      x: 115,
      y: 80,
      label: "Foundry Plant",
      interactive: false,
    },
    {
      id: "f18",
      kind: "Rug",
      x: 55,
      y: 84,
      label: "Forge Rug",
      interactive: false,
    },
    {
      id: "f19",
      kind: "CoffeeMug",
      x: 140,
      y: 78,
      label: "Smith's Coffee",
      interactive: false,
    },
  ],
};
