import type { RoomDef } from "../types";
import { THEMES } from "../themes";
import { SK } from "../palette";

export const midas: RoomDef = {
  agentId: "midas",
  theme: THEMES.quant,
  character: {
    look: {
      hair: SK.hairWhite,
      shirt: "#f5d64a",
      pants: "#2a1a08",
      accessory: "crown",
    },
    home: { x: 82, y: 73 },
    face: 1,
  },
  objects: [
    // Wall items (y 8-40)
    {
      id: "m1",
      kind: "MegaSafe",
      x: 18,
      y: 12,
      layer: "wall",
      label: "Mega Vault",
      scenarios: [
        {
          id: "safe-opening",
          label: "Opening vault",
          anim: "cast",
          stand: { x: 32, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "m2",
      kind: "TickerBoard",
      x: 60,
      y: 10,
      layer: "wall",
      label: "Market Ticker",
      scenarios: [
        {
          id: "ticker-watching",
          label: "Watching markets",
          anim: "stare",
          stand: { x: 74, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "m3",
      kind: "Clock",
      x: 105,
      y: 8,
      layer: "wall",
      label: "Trading Clock",
      interactive: false,
    },
    {
      id: "m4",
      kind: "NeonSign",
      x: 50,
      y: 6,
      layer: "wall",
      label: "Vault Sign",
      props: { text: "VAULT" },
      interactive: false,
    },
    {
      id: "m5",
      kind: "Lantern",
      x: 140,
      y: 12,
      layer: "wall",
      label: "Gold Lantern",
      interactive: false,
    },
    {
      id: "m6",
      kind: "WallArt",
      x: 3,
      y: 16,
      layer: "wall",
      label: "Wealth Portrait",
      interactive: false,
    },
    // Floor items (y 48-88)
    {
      id: "m7",
      kind: "CoinStack",
      x: 12,
      y: 58,
      label: "Coin Stack 1",
      scenarios: [
        {
          id: "coins-counting",
          label: "Counting coins",
          anim: "count",
          stand: { x: 26, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "m8",
      kind: "CoinStack",
      x: 32,
      y: 62,
      label: "Coin Stack 2",
      scenarios: [
        {
          id: "coins-tallying",
          label: "Tallying wealth",
          anim: "count",
          stand: { x: 46, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "m9",
      kind: "CoinStack",
      x: 52,
      y: 56,
      label: "Coin Stack 3",
      interactive: false,
    },
    {
      id: "m10",
      kind: "CoinStack",
      x: 70,
      y: 60,
      label: "Coin Stack 4",
      interactive: false,
    },
    {
      id: "m11",
      kind: "BalanceScale",
      x: 95,
      y: 62,
      label: "Balance Scale",
      scenarios: [
        {
          id: "scale-weighing",
          label: "Weighing assets",
          anim: "cast",
          stand: { x: 89, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "m12",
      kind: "GoldBars",
      x: 125,
      y: 58,
      label: "Gold Bars 1",
      scenarios: [
        {
          id: "gold-inventorying",
          label: "Inventorying bullion",
          anim: "count",
          stand: { x: 119, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "m13",
      kind: "GoldBars",
      x: 140,
      y: 56,
      label: "Gold Bars 2",
      interactive: false,
    },
    {
      id: "m14",
      kind: "LedgerBook",
      x: 18,
      y: 74,
      label: "Ledger Book",
      scenarios: [
        {
          id: "ledger-balancing",
          label: "Balancing books",
          anim: "read",
          stand: { x: 32, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "m15",
      kind: "LedgerBook",
      x: 42,
      y: 76,
      label: "Account Ledger",
      interactive: false,
    },
    {
      id: "m16",
      kind: "JeweledChest",
      x: 70,
      y: 74,
      label: "Jeweled Chest",
      scenarios: [
        {
          id: "chest-appraising",
          label: "Appraising gems",
          anim: "stare",
          stand: { x: 64, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "m17",
      kind: "Abacus",
      x: 98,
      y: 76,
      label: "Counting Abacus",
      scenarios: [
        {
          id: "abacus-calculating",
          label: "Calculating",
          anim: "count",
          stand: { x: 104, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "m18",
      kind: "MechanicalCalc",
      x: 125,
      y: 78,
      label: "Mechanical Calculator",
      scenarios: [
        {
          id: "calc-crunching",
          label: "Crunching numbers",
          anim: "type",
          stand: { x: 119, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "m19",
      kind: "Cat",
      x: 3,
      y: 80,
      label: "Midas Cat",
      scenarios: [
        {
          id: "cat-scratching",
          label: "Scratching Midas-cat",
          anim: "stare",
          stand: { x: 17, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "m20",
      kind: "Rug",
      x: 60,
      y: 84,
      label: "Vault Rug",
      interactive: false,
    },
  ],
};
