import type { RoomDef } from "../types";
import { THEMES } from "../themes";
import { SK } from "../palette";

export const nova: RoomDef = {
  agentId: "nova",
  theme: THEMES.scholar,
  character: {
    look: {
      hair: SK.hairBlonde,
      shirt: "#22ff88",
      pants: "#2a3018",
      accessory: "monocle",
    },
    home: { x: 80, y: 73 },
    face: 1,
  },
  objects: [
    // Wall items (y 8-40)
    {
      id: "n1",
      kind: "Bookshelf",
      x: 10,
      y: 12,
      layer: "wall",
      label: "Tome Shelf",
      props: { variant: "tall" },
      scenarios: [
        {
          id: "shelf-browsing",
          label: "Browsing tomes",
          anim: "read",
          stand: { x: 24, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "n2",
      kind: "Bookshelf",
      x: 50,
      y: 10,
      layer: "wall",
      label: "Archive Shelf",
      props: { variant: "wide" },
      interactive: false,
    },
    {
      id: "n3",
      kind: "Bookshelf",
      x: 95,
      y: 14,
      layer: "wall",
      label: "Reference Shelf",
      props: { variant: "deep" },
      interactive: false,
    },
    {
      id: "n4",
      kind: "Telescope",
      x: 138,
      y: 16,
      layer: "wall",
      label: "Brass Telescope",
      scenarios: [
        {
          id: "telescope-stargazing",
          label: "Stargazing",
          anim: "cast",
          stand: { x: 130, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "n5",
      kind: "Clock",
      x: 65,
      y: 8,
      layer: "wall",
      label: "Pendulum Clock",
      interactive: false,
    },
    {
      id: "n6",
      kind: "Chalkboard",
      x: 28,
      y: 18,
      layer: "wall",
      label: "Theorem Board",
      scenarios: [
        {
          id: "chalk-theorems",
          label: "Writing theorems",
          anim: "type",
          stand: { x: 42, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "n7",
      kind: "WallArt",
      x: 115,
      y: 10,
      layer: "wall",
      label: "Portrait",
      props: { variant: "portrait" },
      interactive: false,
    },
    {
      id: "n8",
      kind: "Lantern",
      x: 5,
      y: 24,
      layer: "wall",
      label: "Wall Sconce",
      interactive: false,
    },
    // Floor items (y 48-88)
    {
      id: "n9",
      kind: "ReadingDesk",
      x: 18,
      y: 56,
      label: "Reading Desk",
      scenarios: [
        {
          id: "desk-referencing",
          label: "Cross-referencing sources",
          anim: "read",
          stand: { x: 32, y: 72 },
          face: 1,
          duration: 5,
        },
      ],
    },
    {
      id: "n10",
      kind: "Microscope",
      x: 48,
      y: 58,
      label: "Brass Microscope",
      scenarios: [
        {
          id: "micro-peering",
          label: "Peering at specimens",
          anim: "stare",
          stand: { x: 56, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "n11",
      kind: "Globe",
      x: 76,
      y: 62,
      label: "World Globe",
      scenarios: [
        {
          id: "globe-mapping",
          label: "Mapping regions",
          anim: "cast",
          stand: { x: 68, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "n12",
      kind: "ScrollRack",
      x: 104,
      y: 56,
      label: "Scroll Rack",
      scenarios: [
        {
          id: "scroll-unfurling",
          label: "Unfurling scrolls",
          anim: "stare",
          stand: { x: 98, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "n13",
      kind: "Herbarium",
      x: 134,
      y: 60,
      label: "Herbarium Collection",
      scenarios: [
        {
          id: "herb-cataloging",
          label: "Cataloging flora",
          anim: "read",
          stand: { x: 126, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "n14",
      kind: "InkwellQuill",
      x: 12,
      y: 74,
      label: "Inkwell & Quill",
      scenarios: [
        {
          id: "ink-annotating",
          label: "Annotating notes",
          anim: "type",
          stand: { x: 24, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "n15",
      kind: "Candelabra",
      x: 42,
      y: 70,
      label: "Candelabra",
      scenarios: [
        {
          id: "candle-lighting",
          label: "Lighting candles",
          anim: "cast",
          stand: { x: 56, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "n16",
      kind: "Candelabra",
      x: 75,
      y: 78,
      label: "Floor Candelabra",
      interactive: false,
    },
    {
      id: "n17",
      kind: "Plant",
      x: 100,
      y: 76,
      label: "Study Plant",
      interactive: false,
    },
    {
      id: "n18",
      kind: "Plant",
      x: 125,
      y: 80,
      label: "Corner Plant",
      interactive: false,
    },
    {
      id: "n19",
      kind: "Rug",
      x: 55,
      y: 82,
      label: "Library Rug",
      interactive: false,
    },
    {
      id: "n20",
      kind: "CoffeeMug",
      x: 148,
      y: 74,
      label: "Scholar's Tea",
      interactive: false,
    },
  ],
};
