import type { RoomDef } from "../types";
import { THEMES } from "../themes";
import { SK } from "../palette";

export const ultron: RoomDef = {
  agentId: "ultron",
  theme: THEMES.bridge,
  character: {
    look: {
      hair: SK.hairBlack,
      shirt: "#22e8ff",
      pants: "#1a2340",
      accessory: "headset",
    },
    home: { x: 78, y: 73 },
    face: 1,
  },
  objects: [
    // Wall items (y 8-40)
    {
      id: "u1",
      kind: "CaptainChair",
      x: 14,
      y: 48,
      label: "Captain's Chair",
      scenarios: [
        {
          id: "chair-commanding",
          label: "Commanding fleet",
          anim: "sit",
          stand: { x: 28, y: 72 },
          face: 1,
          duration: 5,
        },
      ],
    },
    {
      id: "u2",
      kind: "HelmWheel",
      x: 45,
      y: 18,
      layer: "wall",
      label: "Helm Wheel",
      scenarios: [
        {
          id: "wheel-plotting",
          label: "Plotting course",
          anim: "cast",
          stand: { x: 58, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "u3",
      kind: "CRTMonitor",
      x: 80,
      y: 12,
      layer: "wall",
      label: "Telemetry Monitor",
      props: { variant: "green" },
      scenarios: [
        {
          id: "monitor-telemetry",
          label: "Reading incoming telemetry",
          anim: "type",
          stand: { x: 75, y: 72 },
          face: 1,
          duration: 5,
        },
      ],
    },
    {
      id: "u4",
      kind: "CRTMonitor",
      x: 110,
      y: 16,
      layer: "wall",
      label: "Status Display",
      props: { variant: "amber" },
      scenarios: [
        {
          id: "status-monitoring",
          label: "Checking status",
          anim: "stare",
          stand: { x: 104, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "u5",
      kind: "TacticalMap",
      x: 138,
      y: 14,
      layer: "wall",
      label: "Tactical Map",
      scenarios: [
        {
          id: "map-reviewing",
          label: "Reviewing map",
          anim: "stare",
          stand: { x: 130, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "u6",
      kind: "WindowPane",
      x: 3,
      y: 8,
      layer: "wall",
      label: "Night Sky Portal",
      props: { time: "night" },
      interactive: false,
    },
    {
      id: "u7",
      kind: "NeonSign",
      x: 50,
      y: 6,
      layer: "wall",
      label: "Bridge Sign",
      props: { text: "BRIDGE" },
      interactive: false,
    },
    {
      id: "u8",
      kind: "Clock",
      x: 20,
      y: 10,
      layer: "wall",
      label: "Chronometer",
      interactive: false,
    },
    {
      id: "u9",
      kind: "Lantern",
      x: 145,
      y: 8,
      layer: "wall",
      label: "Wall Lantern",
      interactive: false,
    },
    // Floor items (y 48-88)
    {
      id: "u10",
      kind: "BrassCompass",
      x: 12,
      y: 62,
      label: "Brass Compass",
      scenarios: [
        {
          id: "compass-checking",
          label: "Checking bearing",
          anim: "read",
          stand: { x: 24, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "u11",
      kind: "RadioTransmitter",
      x: 32,
      y: 58,
      label: "Radio Transmitter",
      scenarios: [
        {
          id: "radio-hailing",
          label: "Hailing specialists",
          anim: "transmit",
          stand: { x: 45, y: 72 },
          face: 1,
          duration: 4,
        },
      ],
    },
    {
      id: "u12",
      kind: "Periscope",
      x: 62,
      y: 52,
      label: "Periscope",
      scenarios: [
        {
          id: "periscope-scanning",
          label: "Scanning horizon",
          anim: "stare",
          stand: { x: 56, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "u13",
      kind: "StarChart",
      x: 88,
      y: 56,
      label: "Star Chart",
      interactive: false,
    },
    {
      id: "u14",
      kind: "HoloTable",
      x: 108,
      y: 54,
      label: "Holo-Projection Table",
      scenarios: [
        {
          id: "holo-projecting",
          label: "Projecting route",
          anim: "cast",
          stand: { x: 100, y: 72 },
          face: -1,
          duration: 5,
        },
      ],
    },
    {
      id: "u15",
      kind: "CommandConsole",
      x: 136,
      y: 58,
      label: "Command Console",
      scenarios: [
        {
          id: "console-dispatching",
          label: "Dispatching orders",
          anim: "type",
          stand: { x: 128, y: 72 },
          face: -1,
          duration: 4,
        },
      ],
    },
    {
      id: "u16",
      kind: "CoffeeMug",
      x: 24,
      y: 80,
      label: "Bridge Brew",
      scenarios: [
        {
          id: "coffee-sipping",
          label: "Sipping bridge brew",
          anim: "brew",
          stand: { x: 28, y: 72 },
          face: 1,
          duration: 3,
        },
      ],
    },
    {
      id: "u17",
      kind: "Rug",
      x: 40,
      y: 82,
      label: "Tactical Rug",
      interactive: false,
    },
    {
      id: "u18",
      kind: "ServerRack",
      x: 74,
      y: 76,
      label: "Server Rack",
      interactive: false,
    },
    {
      id: "u19",
      kind: "FloorTile",
      x: 110,
      y: 80,
      label: "Floor Tile",
      interactive: false,
    },
    {
      id: "u20",
      kind: "Lantern",
      x: 148,
      y: 78,
      label: "Floor Lantern",
      interactive: false,
    },
  ],
};
